//tealium universal tag - utag.121 ut4.0.201609271031, Copyright 2016 Tealium.com Inc. All Rights Reserved.
window.sidecar=window.sidecar||{};window.sidecar.preboot=window.sidecar.preboot||{};try{(function(id,loader,u){u=utag.o[loader].sender[id]={};u.ev={'view':1};u.event_lookup={"login":"login","prodlist":"prodlist","cartview":"cartview","cartempty":"cartempty","purchase":"purchase"};u.data={};u.data.site_key="";u.base_url="//d3v27wwd40f0xu.cloudfront.net/js/tracking/sidecar_boscovs.js";u.map={"product_upc":"product_id","product_id":"group_id","page_type:product":"prodlist","_cpdisc":"discounts","_csubtotal":"subtotal","order_grand_total":"total","billing_postal_code":"zipcode"};u.extend=[function(a,b){try{if(1){try{b['product_id']=b.product_id.toString()}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['_cpdisc']='0'}}catch(e){utag.DB(e)}},function(a,b){b.order_grand_total=((parseFloat(b._csubtotal)+parseFloat(b._cship)+parseFloat(b._ctax)).toFixed(2)).toString();b._cpdisc="0";}];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};var c,d,e,f;for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}else{h=d.split(":");if(h.length==2&&b[h[0]]==h[1]){g=""+u.event_lookup[u.map[d]];if(g!=""){b._cevent=g}}}}
var _ccat=b._ccat?b._ccat.slice(0):[];var _cprod=b._cprod?b._cprod.slice(0):[];var _cquan=b._cquan?b._cquan.slice(0):[];var _cprice=b._cprice?b._cprice.slice(0):[];var _cpdisc=b._cpdisc?b._cpdisc.slice(0):[];window.sidecar.preboot.site_key=u.data.site_key;if(b._cevent=="login"){window.sidecar.logged_in="1";window.sidecar.user_email=u.data.user_email||b._ccustid||"";if(u.data.new_registrant){window.sidecar.new_registrant=u.data.new_registrant;}}
if(b._cevent=="prodlist"){u.data.group_id=u.data.group_id||_ccat[0]||"";window.sidecar.product_info={"group_id":u.data.group_id};}
if(b._cevent=="cartview"){u.data.product_id=u.data.product_id||_cprod;u.data.quantity=u.data.quantity||_cquan;u.data.unit_price=u.data.unit_price||_cprice;window.sidecar.cart_info={};window.sidecar.cart_info.items=[];for(var i=0;i<u.data.product_id.length;i++){window.sidecar.cart_info.items.push({"product_id":u.data.product_id[i],"quantity":u.data.quantity[i],"unit_price":u.data.unit_price[i]});}}
if(b._cevent=="cartempty"){window.sidecar.cart_info={"items":[]};}
if(u.data.order_id||b._corder){b._cevent="purchase";}
if(b._cevent=="purchase"){u.data.order_id=u.data.order_id||b._corder||"";u.data.subtotal=u.data.subtotal||b._csubtotal||"";u.data.tax=u.data.tax||b._ctax||"";u.data.shipping=u.data.shipping||b._cship||"";if(_cpdisc&&_cpdisc!=""){u.data.sumdisc=0;for(var i=0;i<_cpdisc.length;i++){u.data.sumdisc+=parseFloat(_cpdisc[i]).toFixed(2);}
u.data.sumdisc=u.data.sumdisc+"";}
u.data.totaldiscount=u.data.totaldiscount||u.data.sumdisc||"";u.data.total=u.data.total||b._ctotal;u.data.zipcode=u.data.zipcode||b._czip;u.data.product_id=u.data.product_id||_cprod;u.data.unit_price=u.data.unit_price||_cprice;u.data.quantity=u.data.quantity||_cquan;u.data.discounts=u.data.discounts||_cpdisc;window.sidecar.transactions={"add":"true","data":{"order_id":u.data.order_id,"subtotal":u.data.subtotal,"tax":u.data.tax,"shipping":u.data.shipping,"discounts":u.data.totaldiscount,"total":u.data.total,"zipcode":u.data.zipcode},"items":[],"discounts":[]};for(var i=0;i<u.data.product_id.length;i++){window.sidecar.transactions.items.push({"product_id":u.data.product_id[i],"quantity":u.data.quantity[i],"unit_price":u.data.unit_price[i]});}
for(var i=0;i<u.data.discounts.length;i++){window.sidecar.transactions.discounts.push({"name":"Discount "+i,"amount":u.data.discounts[i]});}}
u.s=document.getElementsByTagName("script")[0];u.scr=document.createElement("script");u.scr.type="text/javascript";u.scr.src=u.base_url;u.s.parentNode.insertBefore(u.scr,u.s);}};utag.o[loader].loader.LOAD(id);})('121','boscovs.main');}catch(e){}
