//tealium universal tag - utag.197 ut4.0.201703161150, Copyright 2017 Tealium.com Inc. All Rights Reserved.
var WidgetData=window.WidgetData||{};window.conciergeReady=jQuery.Deferred();window.addEventListener('GoMoxie:conciergeReady',function(event){conciergeReady.resolve(event);});conciergeReady.then(function(event){console.log("Concierge is Ready.",event);if(WidgetData.transactionComplete){window.GoMoxie.concierge.transactionComplete({transactionTotal:WidgetData.transactionTotal,currentCartValue:WidgetData.currentCartValue,currentCartItems:WidgetData.currentCartItems});}else if(WidgetData.updateSession){window.GoMoxie.concierge.updateSession({transactionTotal:WidgetData.currentCartValue,currentCartValue:WidgetData.currentCartValue,currentCartItems:WidgetData.currentCartItems});}});try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;b.setAttribute("data-concierge","1");b.setAttribute("data-concierge-host","gomoxie.solutions");}
if(o.id){b.id=o.id;}
if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}
l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};u.ev={'view':1};u.initialized=false;u.map={"mox_tenant_name":"tenant_name","mox_event":"event"};u.extend=[function(a,b){try{if((typeof b['page_name']!='undefined'&&b['page_name'].toString().toLowerCase()=='Shopping Cart'.toLowerCase())){b['mox_event']='updateSession'}}catch(e){utag.DB(e)}},function(a,b,c,d,e,f,g){d=b['ut.env'];if(typeof d=='undefined')return;c=[{'dev':'boscovstest'},{'qa':'boscovstest'},{'prod':'boscovs'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['mox_tenant_name']=c[e][f];m=true};};if(m)break};if(!m)b['mox_tenant_name']='boscovs';}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"tenant_name":"","base_url":"//asset.gomoxie.solutions/concierge/","event":"","product_id":[],"product_name":[],"product_quantity":[],"product_unit_price":[],"product_description":[],"product_uom":[],"order_id":"","order_total":"","order_subtotal":""
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_total=u.data.order_total||b._ctotal||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(!u.data.order_subtotal){var cartvalue=0;for(var i=0;i<u.data.product_quantity.length;i++){var quantity=u.data.product_quantity[i],unit_price=u.data.product_unit_price[i],extended_price=parseFloat(quantity)*parseFloat(unit_price);cartvalue+=extended_price;}
u.data.order_subtotal=cartvalue+"";}
WidgetData.currentCartValue=parseFloat(u.data.order_subtotal);WidgetData.currentCartItems=[];for(var i=0;i<u.data.product_id.length;i++){var item={};item.name=u.data.product_name[i]||"";item.skuOrId=u.data.product_id[i];if(u.data.product_unit_price[i]){item.value=parseFloat(u.data.product_unit_price[i]);}
if(u.data.product_quantity[i]){item.quantity=parseInt(u.data.product_quantity[i]);}
if(u.data.product_description[i]){item.description=u.data.product_description[i]||"";}
if(u.data.product_uom[i]){item.uom=u.data.product_uom[i]||"";}
WidgetData.currentCartItems.push(item);}
if(u.data.order_id){WidgetData.transactionTotal=parseFloat(u.data.order_subtotal);WidgetData.transactionComplete=true;}else if(!u.data.order_id&&u.data.event=="updateSession"){WidgetData.updateSession=true;}
};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url+u.data.tenant_name+"/client/concierge-client.js","cb":u.loader_cb,"loc":"script","id":'utag_197'});}};utag.o[loader].loader.LOAD(id);})("197","boscovs.main");}catch(error){utag.DB(error);}
